### ISSUE TITLE
Over 25% increase in CPU usage

### ISSUE THREAD

**Issue by tyfoon** [hassio-addons/addon-zwave-js-ui#451]
# Problem/Motivation

> After upgrading to 1.4 zwave JS is taking between 25-40% of all HASS resources (according to Add On interface)

## Steps to reproduce

Seems related to my upgrade to zwave JS 1.4 or a combination of HASSOS upgrade to 9.4 which I upgraded on the same day.

Hardware platform is an intel NUC.
Zwave JS
Driver Version:
10.3.1
Server Version:
1.24.1

HASS:
Home Assistant 2022.12.5
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

CPU impact (delta seems all generated by zwave JS):

<img width="1229" alt="Screen Shot 2022-12-14 at 18 46 38" src="https://user-images.githubusercontent.com/22179507/207669248-fb2be6b5-ef3d-4a3a-89bc-17fa7afc8285.png">

Below copy of the logs under system>zwave js. No noticeable errors in the core. 

`2022-12-14T17:39:00.981Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:39:01.985Z DRIVER   Dropping message because it contains invalid data
2022-12-14 18:39:01.990 INFO Z-WAVE: Node 11: value updated: 38-0-currentValue 54 => 54
2022-12-14 18:39:06.439 INFO Z-WAVE: Node 9: value updated: 50-1-value-66049 0 => 0
2022-12-14 18:39:07.427 INFO Z-WAVE: Node 9: value updated: 50-2-value-66049 0 => 0
2022-12-14 18:39:09.976 ERROR Z-WAVE-SERVER: Timeout while waiting for a response from the controller (ZW0200)
ZWaveError: Timeout while waiting for a response from the controller (ZW0200)
    at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:3990:23)
    at Driver.sendCommandInternal (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4181:28)
    at Driver.sendCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:4296:15)
    at Proxy.set (/opt/node_modules/@zwave-js/cc/src/cc/MultilevelSwitchCC.ts:238:24)
    at Proxy.MultilevelSwitchCCAPI.<computed> (/opt/node_modules/@zwave-js/cc/src/cc/MultilevelSwitchCC.ts:344:6)
    at ZWaveNode.setValue (/opt/node_modules/zwave-js/src/lib/node/Node.ts:932:29)
    at NodeMessageHandler.handle (/opt/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:23:38)
    at Object.node (/opt/node_modules/@zwave-js/server/dist/lib/server.js:40:96)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:105:99)
    at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:49:45)
2022-12-14 18:39:19.671 INFO Z-WAVE: Node 52: value updated: 113-0-alarmType 0 => 0
2022-12-14 18:39:19.673 INFO Z-WAVE: Node 52: value updated: 113-0-alarmLevel 0 => 0
2022-12-14 18:39:19.677 INFO Z-WAVE: Node 52: value updated: 113-0-Home Security-Motion sensor status 8 => 8
2022-12-14 18:39:19.776 INFO Z-WAVE: Node 52: metadata updated: 48-0-Any
2022-12-14 18:39:19.778 INFO Z-WAVE: Node 52: value updated: 48-0-Any true => true
2022-12-14 18:39:19.855 INFO Z-WAVE: Node 52: metadata updated: 48-0-Any
2022-12-14 18:39:19.856 INFO Z-WAVE: Node 52: value updated: 48-0-Any true => true
2022-12-14T17:39:21.020Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:39:58.849Z DRIVER   Dropping message because it contains invalid data
2022-12-14 18:39:58.856 INFO Z-WAVE: Node 52: metadata updated: 48-0-Any
2022-12-14 18:39:58.859 INFO Z-WAVE: Node 52: value updated: 48-0-Any true => false
2022-12-14 18:40:04.901 INFO Z-WAVE: Node 41: value updated: 32-0-currentValue 99 => 99
2022-12-14 18:40:04.905 INFO Z-WAVE: Node 41: value updated: 32-0-currentValue 99 => 99
2022-12-14 18:40:44.782 INFO APP: GET /health/zwave 200 2.039 ms - 2005
2022-12-14 18:41:10.220 INFO Z-WAVE: Node 41: value updated: 67-0-setpoint-1 18.5 => 18.5
2022-12-14 18:41:48.844 INFO Z-WAVE: Node 15: value updated: 50-1-value-66049 0 => 0
2022-12-14 18:41:49.684 INFO Z-WAVE: Node 15: value updated: 50-2-value-66049 0 => 0
2022-12-14 18:41:50.114 INFO Z-WAVE: Node 49: value updated: 50-0-value-66049 5.9 => 0
2022-12-14 18:41:51.117 INFO Z-WAVE: Node 49: value updated: 50-0-value-66049 0 => 5.7
2022-12-14 18:42:15.060 INFO Z-WAVE: Node 41: value updated: 64-0-mode 0 => 0
2022-12-14 18:42:15.864 INFO Z-WAVE: Node 24: value updated: 128-0-level 0 => 0
2022-12-14 18:42:15.866 INFO Z-WAVE: Node 24: value updated: 128-0-isLow true => true
2022-12-14 18:42:44.804 INFO APP: GET /health/zwave 200 3.836 ms - 2005
2022-12-14 18:43:02.030 INFO Z-WAVE: Node 12: value updated: 50-1-value-66049 0 => 0
2022-12-14 18:43:02.844 INFO Z-WAVE: Node 12: value updated: 50-2-value-66049 0 => 0
2022-12-14 18:43:03.606 INFO Z-WAVE: Node 56: metadata updated: 49-0-Air temperature
2022-12-14 18:43:03.608 INFO Z-WAVE: Node 56: value updated: 49-0-Air temperature 4.9 => 4.9
2022-12-14 18:43:03.876 INFO Z-WAVE: Node 56: metadata updated: 49-0-Humidity
2022-12-14 18:43:03.878 INFO Z-WAVE: Node 56: value updated: 49-0-Humidity 56 => 56
2022-12-14 18:43:04.814 INFO Z-WAVE: Node 56: value updated: 128-0-level 100 => 100
2022-12-14 18:43:04.816 INFO Z-WAVE: Node 56: value updated: 128-0-isLow false => false
2022-12-14 18:43:05.109 INFO Z-WAVE: Node 56: metadata updated: 49-0-Illuminance
2022-12-14 18:43:05.110 INFO Z-WAVE: Node 56: value updated: 49-0-Illuminance 0 => 0
2022-12-14 18:43:05.536 INFO Z-WAVE: Node 56: metadata updated: 49-0-Ultraviolet
2022-12-14 18:43:05.537 INFO Z-WAVE: Node 56: value updated: 49-0-Ultraviolet 0 => 0
2022-12-14 18:43:14.084 INFO Z-WAVE: Node 58: metadata updated: 49-0-Air temperature
2022-12-14 18:43:14.087 INFO Z-WAVE: Node 58: value updated: 49-0-Air temperature -1.9 => -1.9
2022-12-14 18:43:14.218 INFO Z-WAVE: Node 58: metadata updated: 49-0-Humidity
2022-12-14 18:43:14.220 INFO Z-WAVE: Node 58: value updated: 49-0-Humidity 76 => 76
2022-12-14 18:43:15.011 INFO Z-WAVE: Node 58: value updated: 128-0-level 100 => 100
2022-12-14 18:43:15.013 INFO Z-WAVE: Node 58: value updated: 128-0-isLow false => false
2022-12-14 18:43:15.087 INFO Z-WAVE: Node 58: metadata updated: 49-0-Illuminance
2022-12-14 18:43:15.090 INFO Z-WAVE: Node 58: value updated: 49-0-Illuminance 1 => 2
2022-12-14 18:43:15.209 INFO Z-WAVE: Node 58: metadata updated: 49-0-Ultraviolet
2022-12-14 18:43:15.212 INFO Z-WAVE: Node 58: value updated: 49-0-Ultraviolet 0 => 0
2022-12-14 18:43:20.026 INFO Z-WAVE: Node 41: metadata updated: 49-0-Air temperature
2022-12-14 18:43:20.028 INFO Z-WAVE: Node 41: value updated: 49-0-Air temperature 9.6 => 9.6
2022-12-14 18:44:07.132 INFO Z-WAVE: Node 9: value updated: 50-1-value-66049 0 => 0
2022-12-14 18:44:07.936 INFO Z-WAVE: Node 9: value updated: 50-2-value-66049 0 => 0
2022-12-14 18:44:25.113 INFO Z-WAVE: Node 41: value updated: 32-0-currentValue 99 => 99
2022-12-14 18:44:25.116 INFO Z-WAVE: Node 41: value updated: 32-0-currentValue 99 => 99
2022-12-14 18:44:42.781 INFO Z-WAVE: Node 11: value updated: 50-0-value-66049 18.1 => 17.8
2022-12-14 18:44:44.827 INFO APP: GET /health/zwave 200 3.746 ms - 2005
2022-12-14 18:45:30.292 INFO Z-WAVE: Node 41: value updated: 67-0-setpoint-1 18.5 => 18.5
2022-12-14 18:45:31.543 INFO Z-WAVE: Node 66: metadata updated: 49-1-Power
2022-12-14 18:45:31.546 INFO Z-WAVE: Node 66: value updated: 49-1-Power 9.2 => 9.1
2022-12-14 18:46:18.408 INFO Z-WAVE: Node 24: value updated: 128-0-level 0 => 0
2022-12-14 18:46:18.411 INFO Z-WAVE: Node 24: value updated: 128-0-isLow true => true
2022-12-14 18:46:35.201 INFO Z-WAVE: Node 41: value updated: 64-0-mode 0 => 0
2022-12-14 18:46:40.424 INFO Z-WAVE: Node 11: value updated: 50-0-value-66049 17.8 => 17.1
2022-12-14 18:46:44.413 INFO Z-WAVE: Node 11: value updated: 50-0-value-66049 17.1 => 18.2
2022-12-14 18:46:44.848 INFO APP: GET /health/zwave 200 3.009 ms - 2005
2022-12-14 18:46:49.018 INFO Z-WAVE: Node 15: value updated: 50-1-value-66049 0 => 0
2022-12-14 18:46:49.989 INFO Z-WAVE: Node 15: value updated: 50-2-value-66049 0 => 0
2022-12-14 18:47:40.394 INFO Z-WAVE: Node 41: metadata updated: 49-0-Air temperature
2022-12-14 18:47:40.396 INFO Z-WAVE: Node 41: value updated: 49-0-Air temperature 9.6 => 9.5
2022-12-14T17:47:45.804Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:45.806Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:45.807Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:45.810Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:45.814Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:46.816Z DRIVER   Dropping message because it contains invalid data
2022-12-14 18:47:46.824 INFO Z-WAVE: Node 11: value updated: 38-0-currentValue 54 => 0
2022-12-14 18:47:46.833 INFO Z-WAVE: Node 11: value updated: 50-0-value-66049 18.2 => 3.3
2022-12-14 18:47:47.232 INFO Z-WAVE: Node 11: value updated: 50-0-value-66049 3.3 => 0
2022-12-14T17:47:54.815Z CNTRLR   No response from controller after 1/3 attempts. Scheduling next try in 100 ms.
2022-12-14T17:47:55.925Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:55.927Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:55.929Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:55.930Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:55.932Z DRIVER   Dropping message because it contains invalid data
2022-12-14T17:47:56.937Z DRIVER   Dropping message because it contains invalid data
2022-12-14 18:47:56.943 INFO Z-WAVE: Node 11: value updated: 38-0-currentValue 0 => 0`

And the host logs:

`Dec 14 13:53:06 homeassistant kernel: audit: type=1334 audit(1671025986.132:451): prog-id=138 op=LOAD
Dec 14 13:53:06 homeassistant kernel: audit: type=1300 audit(1671025986.132:451): arch=c000003e syscall=321 success=yes exit=18 a0=5 a1=c0001bb7c8 a2=78 a3=c00032b1f8 items=0 ppid=62622 pid=62633 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Dec 14 13:53:06 homeassistant kernel: audit: type=1327 audit(1671025986.132:451): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F7661722F72756E2F646F636B65722F636F6E7461696E6572642F6461656D6F6E2F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F61396461666137
Dec 14 13:53:06 homeassistant kernel: eth0: renamed from veth18dad61
Dec 14 13:53:06 homeassistant kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth32bef36: link becomes ready
Dec 14 13:53:06 homeassistant kernel: hassio: port 8(veth32bef36) entered blocking state
Dec 14 13:53:06 homeassistant kernel: hassio: port 8(veth32bef36) entered forwarding state
Dec 14 13:53:06 homeassistant NetworkManager[336]: <info>  [1671025986.4889] device (veth32bef36): carrier: link connected
Dec 14 14:11:27 homeassistant systemd-journald[119]: Data hash table of /var/log/journal/54f8260a036542fa99d7457006dc780b/system.journal has a fill level at 75.0 (174763 of 233016 items, 134217728 file size, 767 bytes per hash table item), suggesting rotation.
Dec 14 14:11:27 homeassistant systemd-journald[119]: /var/log/journal/54f8260a036542fa99d7457006dc780b/system.journal: Journal header limits reached or header out-of-date, rotating.
Dec 14 14:41:35 homeassistant systemd[1]: var-lib-docker-overlay2-6f4c0ab431c027b187f99d1a63847a59cb6c7da2564102472afbccb7991950c3-merged.mount: Deactivated successfully.
Dec 14 14:41:35 homeassistant systemd[1]: mnt-data-docker-overlay2-6f4c0ab431c027b187f99d1a63847a59cb6c7da2564102472afbccb7991950c3-merged.mount: Deactivated successfully.
Dec 14 14:41:38 homeassistant systemd[1]: var-lib-docker-overlay2-64cfa23f374460a240e5612e1535c01f4624084ed5f8507e3dfebe77dc349019-merged.mount: Deactivated successfully.
Dec 14 14:41:38 homeassistant systemd[1]: mnt-data-docker-overlay2-64cfa23f374460a240e5612e1535c01f4624084ed5f8507e3dfebe77dc349019-merged.mount: Deactivated successfully.
Dec 14 14:41:45 homeassistant systemd[1]: var-lib-docker-overlay2-c942ea9c560635dc77759f969acb824fdc2d99caac3c8e40c4d7cd1dd4a7205e-merged.mount: Deactivated successfully.
Dec 14 14:41:45 homeassistant systemd[1]: mnt-data-docker-overlay2-c942ea9c560635dc77759f969acb824fdc2d99caac3c8e40c4d7cd1dd4a7205e-merged.mount: Deactivated successfully.
Dec 14 14:41:47 homeassistant systemd[1]: var-lib-docker-overlay2-d095124a3fe4c6c729477bd77ed9c376943ac972c62328baeb87f0a20d2d8ed6-merged.mount: Deactivated successfully.
Dec 14 14:41:47 homeassistant systemd[1]: mnt-data-docker-overlay2-d095124a3fe4c6c729477bd77ed9c376943ac972c62328baeb87f0a20d2d8ed6-merged.mount: Deactivated successfully.
Dec 14 14:41:48 homeassistant systemd[1]: var-lib-docker-overlay2-3051262a1985e13ad4d6d564267c91ae2a79a52bd0f45b447243fb1d3b0e7973-merged.mount: Deactivated successfully.
Dec 14 14:41:48 homeassistant systemd[1]: mnt-data-docker-overlay2-3051262a1985e13ad4d6d564267c91ae2a79a52bd0f45b447243fb1d3b0e7973-merged.mount: Deactivated successfully.
Dec 14 14:41:51 homeassistant systemd[1]: var-lib-docker-overlay2-01ecda2d30d27fa06b5a3db1db8c10b937c3112582e9b7db8758f3c100e2dbe2-merged.mount: Deactivated successfully.
Dec 14 14:41:51 homeassistant systemd[1]: mnt-data-docker-overlay2-01ecda2d30d27fa06b5a3db1db8c10b937c3112582e9b7db8758f3c100e2dbe2-merged.mount: Deactivated successfully.
Dec 14 14:41:52 homeassistant systemd[1]: var-lib-docker-overlay2-f92ba45fd708d0809d017593a220e61999d2a496da07373bc38fcaf6cd51ee1e-merged.mount: Deactivated successfully.
Dec 14 14:41:52 homeassistant systemd[1]: mnt-data-docker-overlay2-f92ba45fd708d0809d017593a220e61999d2a496da07373bc38fcaf6cd51ee1e-merged.mount: Deactivated successfully.
Dec 14 14:41:52 homeassistant systemd[1]: var-lib-docker-overlay2-2992dead0696df5f1967d176bcb813c7c9ff91530accdca54c963d180ebba77b-merged.mount: Deactivated successfully.
Dec 14 14:41:52 homeassistant systemd[1]: mnt-data-docker-overlay2-2992dead0696df5f1967d176bcb813c7c9ff91530accdca54c963d180ebba77b-merged.mount: Deactivated successfully.
Dec 14 14:41:53 homeassistant systemd[1]: var-lib-docker-overlay2-51c4d17068cdf98be69fcf2d5ba2fc7508095fb758226568d55e9469add14f4f-merged.mount: Deactivated successfully.
Dec 14 14:41:53 homeassistant systemd[1]: mnt-data-docker-overlay2-51c4d17068cdf98be69fcf2d5ba2fc7508095fb758226568d55e9469add14f4f-merged.mount: Deactivated successfully.
Dec 14 14:41:53 homeassistant systemd[1]: var-lib-docker-overlay2-17b5daaae211f48b5058c1ae3e1fef1aabd0699682f069d9c399ffbf26d3a3c9-merged.mount: Deactivated successfully.
Dec 14 14:41:53 homeassistant systemd[1]: mnt-data-docker-overlay2-17b5daaae211f48b5058c1ae3e1fef1aabd0699682f069d9c399ffbf26d3a3c9-merged.mount: Deactivated successfully.
Dec 14 14:41:57 homeassistant kernel: kauditd_printk_skb: 29 callbacks suppressed
Dec 14 14:41:57 homeassistant kernel: audit: type=1334 audit(1671028917.493:463): prog-id=0 op=UNLOAD
Dec 14 14:41:57 homeassistant systemd[1]: docker-db9c38460e20421f7ded2d10db6c658dd14aee946e7b9b335ccbb956ff45edf7.scope: Deactivated successfully.
Dec 14 14:41:57 homeassistant systemd[1]: docker-db9c38460e20421f7ded2d10db6c658dd14aee946e7b9b335ccbb956ff45edf7.scope: Consumed 32.617s CPU time.
Dec 14 14:41:57 homeassistant kernel: audit: type=1334 audit(1671028917.507:464): prog-id=0 op=UNLOAD
Dec 14 14:41:57 homeassistant dockerd[410]: time="2022-12-14T14:41:57.530360064Z" level=info msg="shim disconnected" id=db9c38460e20421f7ded2d10db6c658dd14aee946e7b9b335ccbb956ff45edf7
Dec 14 14:41:57 homeassistant dockerd[410]: time="2022-12-14T14:41:57.530956838Z" level=warning msg="cleaning up after shim disconnected" id=db9c38460e20421f7ded2d10db6c658dd14aee946e7b9b335ccbb956ff45edf7 namespace=moby
Dec 14 14:41:57 homeassistant dockerd[410]: time="2022-12-14T14:41:57.531111020Z" level=info msg="cleaning up dead shim"
Dec 14 14:41:57 homeassistant dockerd[403]: time="2022-12-14T14:41:57.533457234Z" level=info msg="ignoring event" container=db9c38460e20421f7ded2d10db6c658dd14aee946e7b9b335ccbb956ff45edf7 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Dec 14 14:41:57 homeassistant dockerd[410]: time="2022-12-14T14:41:57.549119817Z" level=warning msg="cleanup warnings time=\"2022-12-14T14:41:57Z\" level=info msg=\"starting signal loop\" namespace=moby pid=69876 runtime=io.containerd.runc.v2\n"
Dec 14 14:41:57 homeassistant systemd[1]: var-lib-docker-overlay2-0132c88383b4e4a75914657d9f6da003067ed97e833124870eb8ecd32bb87531-merged.mount: Deactivated successfully.
Dec 14 14:41:57 homeassistant systemd[1]: mnt-data-docker-overlay2-0132c88383b4e4a75914657d9f6da003067ed97e833124870eb8ecd32bb87531-merged.mount: Deactivated successfully.
Dec 14 14:41:59 homeassistant systemd[1]: var-lib-docker-overlay2-64ba10a5d7dceca978623d8d1c253d5c5b5c9ab7ac9a31781a0b97d1adfb4307\x2dinit-merged.mount: Deactivated successfully.
Dec 14 14:41:59 homeassistant systemd[1]: mnt-data-docker-overlay2-64ba10a5d7dceca978623d8d1c253d5c5b5c9ab7ac9a31781a0b97d1adfb4307\x2dinit-merged.mount: Deactivated successfully.
Dec 14 14:41:59 homeassistant dockerd[410]: time="2022-12-14T14:41:59.921293921Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Dec 14 14:41:59 homeassistant dockerd[410]: time="2022-12-14T14:41:59.921827425Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Dec 14 14:41:59 homeassistant dockerd[410]: time="2022-12-14T14:41:59.921919923Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Dec 14 14:41:59 homeassistant dockerd[410]: time="2022-12-14T14:41:59.922268436Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/24131bcff1e8a87dd1ab1242ca6fe29d161f972db024b8693b45f1f2869a5314 pid=69897 runtime=io.containerd.runc.v2
Dec 14 14:41:59 homeassistant systemd[1]: Started libcontainer container 24131bcff1e8a87dd1ab1242ca6fe29d161f972db024b8693b45f1f2869a5314.
Dec 14 14:41:59 homeassistant kernel: audit: type=1334 audit(1671028919.989:465): prog-id=140 op=LOAD
Dec 14 14:41:59 homeassistant kernel: audit: type=1334 audit(1671028919.990:466): prog-id=141 op=LOAD
Dec 14 14:41:59 homeassistant kernel: audit: type=1300 audit(1671028919.990:466): arch=c000003e syscall=321 success=yes exit=16 a0=5 a1=c000195a30 a2=78 a3=c0001dd3c8 items=0 ppid=69897 pid=69908 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Dec 14 14:41:59 homeassistant kernel: audit: type=1327 audit(1671028919.990:466): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F7661722F72756E2F646F636B65722F636F6E7461696E6572642F6461656D6F6E2F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F32343133316263
Dec 14 14:41:59 homeassistant kernel: audit: type=1334 audit(1671028919.990:467): prog-id=142 op=LOAD
Dec 14 14:41:59 homeassistant kernel: audit: type=1300 audit(1671028919.990:467): arch=c000003e syscall=321 success=yes exit=18 a0=5 a1=c0001957c8 a2=78 a3=c0001dd418 items=0 ppid=69897 pid=69908 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc" exe="/usr/bin/runc" subj=unconfined key=(null)
Dec 14 14:41:59 homeassistant kernel: audit: type=1327 audit(1671028919.990:467): proctitle=72756E63002D2D726F6F74002F7661722F72756E2F646F636B65722F72756E74696D652D72756E632F6D6F6279002D2D6C6F67002F7661722F72756E2F646F636B65722F636F6E7461696E6572642F6461656D6F6E2F696F2E636F6E7461696E6572642E72756E74696D652E76322E7461736B2F6D6F62792F32343133316263
Dec 14 14:41:59 homeassistant kernel: audit: type=1334 audit(1671028919.990:468): prog-id=0 op=UNLOAD
Dec 14 15:21:14 homeassistant kernel: kauditd_printk_skb: 4 callbacks suppressed
Dec 14 15:21:14 homeassistant kernel: audit: type=1334 audit(1671031274.928:471): prog-id=144 op=LOAD
Dec 14 15:21:14 homeassistant kernel: audit: type=1334 audit(1671031274.928:472): prog-id=145 op=LOAD
Dec 14 15:21:14 homeassistant kernel: audit: type=1334 audit(1671031274.928:473): prog-id=146 op=LOAD
Dec 14 15:21:14 homeassistant systemd[1]: Starting Hostname Service...
Dec 14 15:21:15 homeassistant systemd[1]: Started Hostname Service.
Dec 14 15:21:15 homeassistant kernel: audit: type=1334 audit(1671031275.310:474): prog-id=147 op=LOAD
Dec 14 15:21:15 homeassistant kernel: audit: type=1334 audit(1671031275.310:475): prog-id=148 op=LOAD
Dec 14 15:21:15 homeassistant kernel: audit: type=1334 audit(1671031275.310:476): prog-id=149 op=LOAD
Dec 14 15:21:15 homeassistant systemd[1]: Starting Time & Date Service...
Dec 14 15:21:15 homeassistant systemd[1]: Started Time & Date Service.
Dec 14 15:21:45 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Dec 14 15:21:45 homeassistant kernel: audit: type=1334 audit(1671031305.361:477): prog-id=0 op=UNLOAD
Dec 14 15:21:45 homeassistant kernel: audit: type=1334 audit(1671031305.361:478): prog-id=0 op=UNLOAD
Dec 14 15:21:45 homeassistant kernel: audit: type=1334 audit(1671031305.361:479): prog-id=0 op=UNLOAD
Dec 14 15:21:45 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Dec 14 15:21:45 homeassistant kernel: audit: type=1334 audit(1671031305.710:480): prog-id=0 op=UNLOAD
Dec 14 15:21:45 homeassistant kernel: audit: type=1334 audit(1671031305.710:481): prog-id=0 op=UNLOAD
Dec 14 15:21:45 homeassistant kernel: audit: type=1334 audit(1671031305.710:482): prog-id=0 op=UNLOAD
Dec 14 15:43:42 homeassistant systemd-journald[119]: Data hash table of /var/log/journal/54f8260a036542fa99d7457006dc780b/system.journal has a fill level at 75.0 (174763 of 233016 items, 134217728 file size, 767 bytes per hash table item), suggesting rotation.
Dec 14 15:43:42 homeassistant systemd-journald[119]: /var/log/journal/54f8260a036542fa99d7457006dc780b/system.journal: Journal header limits reached or header out-of-date, rotating.
Dec 14 17:27:55 homeassistant kernel: audit: type=1334 audit(1671038875.855:483): prog-id=150 op=LOAD
Dec 14 17:27:55 homeassistant kernel: audit: type=1334 audit(1671038875.855:484): prog-id=151 op=LOAD
Dec 14 17:27:55 homeassistant kernel: audit: type=1334 audit(1671038875.856:485): prog-id=152 op=LOAD
Dec 14 17:27:55 homeassistant systemd[1]: Starting Hostname Service...
Dec 14 17:27:56 homeassistant systemd[1]: Started Hostname Service.
Dec 14 17:27:56 homeassistant kernel: audit: type=1334 audit(1671038876.271:486): prog-id=153 op=LOAD
Dec 14 17:27:56 homeassistant kernel: audit: type=1334 audit(1671038876.271:487): prog-id=154 op=LOAD
Dec 14 17:27:56 homeassistant kernel: audit: type=1334 audit(1671038876.271:488): prog-id=155 op=LOAD
Dec 14 17:27:56 homeassistant systemd[1]: Starting Time & Date Service...
Dec 14 17:27:56 homeassistant systemd[1]: Started Time & Date Service.
Dec 14 17:28:26 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Dec 14 17:28:26 homeassistant kernel: audit: type=1334 audit(1671038906.316:489): prog-id=0 op=UNLOAD
Dec 14 17:28:26 homeassistant kernel: audit: type=1334 audit(1671038906.316:490): prog-id=0 op=UNLOAD
Dec 14 17:28:26 homeassistant kernel: audit: type=1334 audit(1671038906.316:491): prog-id=0 op=UNLOAD
Dec 14 17:28:26 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Dec 14 17:28:26 homeassistant kernel: audit: type=1334 audit(1671038906.684:492): prog-id=0 op=UNLOAD
Dec 14 17:28:26 homeassistant kernel: audit: type=1334 audit(1671038906.684:493): prog-id=0 op=UNLOAD
Dec 14 17:28:26 homeassistant kernel: audit: type=1334 audit(1671038906.684:494): prog-id=0 op=UNLOAD
Dec 14 17:29:12 homeassistant systemd-journald[119]: Data hash table of /var/log/journal/54f8260a036542fa99d7457006dc780b/system.journal has a fill level at 75.0 (174764 of 233016 items, 134217728 file size, 767 bytes per hash table item), suggesting rotation.
Dec 14 17:29:12 homeassistant systemd-journald[119]: /var/log/journal/54f8260a036542fa99d7457006dc780b/system.journal: Journal header limits reached or header out-of-date, rotating.
Dec 14 17:50:40 homeassistant kernel: audit: type=1334 audit(1671040240.633:495): prog-id=156 op=LOAD
Dec 14 17:50:40 homeassistant systemd[1]: Started Journal Gateway Service.
Dec 14 17:50:40 homeassistant systemd-journal-gatewayd[94998]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
`

**Comment by tyfoon** [comment]
Ok. This is solved.

Turns out that the OS upgrade restarted the host which in turn assigned the USB ports differently (my assumption). zwave JS was competing with Ramses RF for the same port.

**Comment by frenck** [comment]
Morning! Glad you got it figured out 👍 

../Frenck
