### ISSUE TITLE
Error upgrading to 1.6.1

### ISSUE THREAD

**Issue by Anders-Falk** [hassio-addons/addon-zwave-js-ui#461]
# Problem/Motivation

Running on Raspberry Pi 4

Providing the log:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 23:02:03 (4 occurrences)
Last logged: 23:03:40

[547019782032] Error updating Z-Wave JS UI: Can't install ghcr.io/hassio-addons/zwave-js-ui/aarch64:1.6.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.6.1&fromImage=ghcr.io%2Fhassio-addons%2Fzwave-js-ui%2Faarch64&platform=linux%2Farm64: Internal Server Error ("received unexpected HTTP status: 500 Internal Server Error")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/hassio-addons/zwave-js-ui/aarch64:1.6.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.6.1&fromImage=ghcr.io%2Fhassio-addons%2Fzwave-js-ui%2Faarch64&platform=linux%2Farm64: Internal Server Error ("received unexpected HTTP status: 500 Internal Server Error")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Z-Wave JS UI: Can't install ghcr.io/hassio-addons/zwave-js-ui/aarch64:1.6.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.6.1&fromImage=ghcr.io%2Fhassio-addons%2Fzwave-js-ui%2Faarch64&platform=linux%2Farm64: Internal Server Error ("received unexpected HTTP status: 500 Internal Server Error")
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Andware** [comment]
I have had the same problem. Solved it in that I removed the check mark by taking a backup then ran the update through

**Comment by Anders-Falk** [comment]
I usually have that unchecked. Tried now for the third time and now it works somehow. This can be closed from my perspective.

//Anders

**Comment by frenck** [comment]
This issue was caused by an outage last night @ GitHub (where the Docker images of this add-on are hosted). GitHub has resolved its issues and everything is fully operational again.

../Frenck

**Comment by yodashut** [comment]
I had to go into SSH in home assistant and rename the docker container in the error and now when I reload, it works.

**Comment by frenck** [comment]
@yodashut that is never the right solution in this managed environment. Please use the managed tools available instead.
