### ISSUE TITLE
RangeError: Maximum call stack size exceeded after update to 1.8.1

### ISSUE THREAD

**Issue by RemCom** [hassio-addons/addon-zwave-js-ui#493]
# Problem/Motivation

After updating to 1.8.1 plugins doesnt start and gives

```
RangeError: Maximum call stack size exceeded
    at CronDate.findNext (/opt/node_modules/croner/dist/croner.min.cjs:1:5663)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:6673)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7231)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7029)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7231)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7029)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7231)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7029)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7231)
    at CronDate.recurse (/opt/node_modules/croner/dist/croner.min.cjs:1:7029)
```

**Comment by RemCom** [comment]
i found what is causing the issue. After the cron format was extra whitespace causing the code to crash

**Comment by Hexagon** [comment]
@RemCom Hmm! This is very interesting!

Is it possible to see which version of croner were used? 

An extra whitespace should normally not cause Maximum call stack exceeded.

In your case the version could be extracted from `/opt/node_modules/croner/package.json`
