### ISSUE TITLE
Various Z-wave errors in the logs and so automations using z-wave entities are freezing after updating to 1.15.x

### ISSUE THREAD

**Issue by alray31** [hassio-addons/addon-zwave-js-ui#548]
# Problem/Motivation

Some automations using z-wave devices stopped working reliably. When the automation stops working, there is always a corresponding z-wave error in HA log. When looking at all the errors, it looks like there are general unstability in my network that was not there before the update.  Rebooting the HA or z-wave JS UI has no effect.

## Expected behavior

Z-wave network to stay stable after 1.15.x update

## Actual behavior

Unstable z-wave network, many different errors:
ZW0204
ZW1405
''Unexpected error for if at pos 1: tuple index out of range''
''NotFoundError: Configuration parameter with value ID 26-112-0-22 could not be found''
and maybe more

## Steps to reproduce

Updating to 1.15.1 caused the problem,
Updating to 1.15.2, problem still there
restored 1.15.1 problem still there 
Restoring 1.14 brings back normal behavior with stable z-wave network, no more errors in the log

## Additional info
Using a aeotec z-stick 7 on firmware 7.19.2
My Z-wave network has always been stable except for the infamous ''dead nodes'' issue that happen every now and then, but I never had this amount of z-wave related errors causing automations to fail before updating to 1.15.x. 

## Errors in the log:
```
Logger: homeassistant.components.automation.test_switch
Source: helpers/script.py:420
Integration: Automatisation (documentation, issues)
First occurred: 26 juillet 2023 à 21:58:05 (1 occurrences)
Last logged: 26 juillet 2023 à 21:58:05

Éclairage comptoir OFF (down keypress x1): Error executing script. Error for device at pos 3: Node(node_id=20) - FailedZWaveCommand: Z-Wave error 204: The node did not acknowledge the command (ZW0204)
```
```
Logger: homeassistant.components.automation.test_switch
Source: helpers/script.py:420
Integration: Automatisation (documentation, issues)
First occurred: 26 juillet 2023 à 21:58:05 (1 occurrences)
Last logged: 26 juillet 2023 à 21:58:05

Éclairage comptoir OFF (down keypress x1): Error executing script. Error for device at pos 3: Node(node_id=20) - FailedZWaveCommand: Z-Wave error 204: The node did not acknowledge the command (ZW0204)
```
```
Logger: homeassistant.components.automation.test_switch
Source: components/automation/__init__.py:680
Integration: Automatisation (documentation, issues)
First occurred: 26 juillet 2023 à 21:58:05 (1 occurrences)
Last logged: 26 juillet 2023 à 21:58:05

Error while executing automation automation.test_switch: Node(node_id=20) - FailedZWaveCommand: Z-Wave error 204: The node did not acknowledge the command (ZW0204)
```
```
Logger: homeassistant.components.automation.eclairage_comptoir_on
Source: helpers/script.py:420
Integration: Automatisation (documentation, issues)
First occurred: 26 juillet 2023 à 22:08:17 (1 occurrences)
Last logged: 26 juillet 2023 à 22:08:17

Éclairage comptoir ON (up keypress x1): Error executing script. Error for device at pos 3: Node(node_id=20) - FailedZWaveCommand: Z-Wave error 1405: The node failed to decode the message. (ZW1405)
```
```
Logger: homeassistant.components.automation.eclairage_comptoir_on
Source: components/automation/__init__.py:680
Integration: Automatisation (documentation, issues)
First occurred: 26 juillet 2023 à 22:08:17 (1 occurrences)
Last logged: 26 juillet 2023 à 22:08:17

Error while executing automation automation.eclairage_comptoir_on: Node(node_id=20) - FailedZWaveCommand: Z-Wave error 1405: The node failed to decode the message. (ZW1405)
```

I dont understand this one, I'm not using mqtt for z-wavejs ui:
```
Logger: homeassistant.config_entries
Source: config_entries.py:1257
First occurred: 26 juillet 2023 à 22:13:42 (1 occurrences)
Last logged: 26 juillet 2023 à 22:13:42

Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Failed to connect: Cannot connect to host a0d7b954-zwavejs2mqtt:3001 ssl:default [Connect call failed ('172.30.33.1', 3001)]; Retrying in background
```
```
Logger: homeassistant.components.automation.status_lumiere_chambre_william
Source: components/zwave_js/services.py:93
Integration: Automatisation (documentation, issues)
First occurred: 26 juillet 2023 à 22:13:42 (3 occurrences)
Last logged: 26 juillet 2023 à 22:13:42

Status lumière chambre William : If at step 1: Error executing script. Unexpected error for device at pos 1: tuple index out of range
Status lumière chambre William : Error executing script. Unexpected error for if at pos 1: tuple index out of range
While executing automation automation.status_lumiere_chambre_william
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 719, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 71, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/device_action.py", line 275, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/services.py", line 448, in async_set_config_parameter
    raise_exceptions_from_results(nodes_list, results)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/services.py", line 91, in raise_exceptions_from_results
    lines = [
            ^
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/services.py", line 93, in <genexpr>
    f"{zwave_object} - {error.__class__.__name__}: {error.args[0]}"
                                                    ~~~~~~~~~~^^^
IndexError: tuple index out of range
```

```
Logger: homeassistant.components.automation.lampe_william_statis
Source: helpers/script.py:420
Integration: Automatisation (documentation, issues)
First occurred: 26 juillet 2023 à 22:14:19 (2 occurrences)
Last logged: 26 juillet 2023 à 22:14:19

Lampe william status: If at step 1: Error executing script. Error for device at pos 1: Node(node_id=26) - NotFoundError: Configuration parameter with value ID 26-112-0-22 could not be found
Lampe william status: Error executing script. Error for if at pos 1: Node(node_id=26) - NotFoundError: Configuration parameter with value ID 26-112-0-22 could not be found
```

![image](https://github.com/hassio-addons/addon-zwave-js-ui/assets/115857857/59eac362-a037-45df-a014-daf4d87d2639)
![image](https://github.com/hassio-addons/addon-zwave-js-ui/assets/115857857/a78f2bdf-531d-4647-b051-406f6b987142)
![image](https://github.com/hassio-addons/addon-zwave-js-ui/assets/115857857/3ab7184a-05be-4122-a31e-20c03c81eb66)
![image](https://github.com/hassio-addons/addon-zwave-js-ui/assets/115857857/e18a6e7e-48c3-4472-9a3f-5bd8af9a5264)
![image](https://github.com/hassio-addons/addon-zwave-js-ui/assets/115857857/94c0af86-a008-4c91-9a6c-b351454017c5)

**Comment by alray31** [comment]
Hold on, I think I just found why i'm having so much errors, they are almost all on nodes 20 and 26 and both these nodes are the same device model, HomeSeer switches with indicator leds. For an unknown reason, all my automations calling to change the switches leds colors lost their values. I'm making the correction to these automations and will try to update again to 1.15.2 and see if there are still some errors.

But why would my automations lose the value that was set for a parameter change when it worked fine for months?

**Comment by alray31** [comment]
Well I had to redo all my automations using z-ware parameter changes so they have their endpoint defined. I tought all problems with that were already solved in a recent update.

for the ''tuple index out of range''' errors, I had to completely redo these automations from scratch. 

Not sure what was going on, but redoing affacted automations cleared all error in the log.
