### ISSUE TITLE
Update: Problem still there in the latest release, 1.15.9. Zwave-js-ui stops working if upgrade after 1.15.2 with a Silicon Labs 700 usb controller.

### ISSUE THREAD

**Issue by magne74** [hassio-addons/addon-zwave-js-ui#558]
# Problem:
Location 1: When upgrade to 1.15.3 or higher, it looks like everything is ok, but it's not. It stops working. Can't ping, no respons. If I try to downgrade, it doesn't even start again. Must do a total reinstall from a system back-up. Location 2: Doesn't have the same issue at home with a z-wavee.me usb 500 stick.

Firmware on Silicon Labs stick:  7.19.1

Will a firmware upgrade help?

**Comment by gburtscher** [comment]
Hi all, the issue is still here. I´ve tried to install the 1.15.8 - but it´s not working. I´ve  a RaZberry 7 Pro module.  FW: v7.6
SDK: v7.15.4. 
And yes:  the only way to recover is a complete restore of the entire HASS  FULL-backup. 

My HASS installation: 
Home Assistant 2023.8.4 Supervisor 2023.08.1 Operating System 10.5 Frontend 20230802.1 - latest 

What I´ve seen in the logs is: 
read errors and timeout on multisensor nodes (all my Fibaro FGS2xx, and some of the Fibaro Roller shutters).
eg my sensative guard strips worked, but my Fibaro switches FGS223 (FW v3.2) didn´t 

I´ve tried it on every update (1.15.3, 1.15.4 .... 1.15.8) - same result. At the moment I´m on 1.15.0

Is there an idea how to solve it?

**Comment by gburtscher** [comment]
Ok I´ve tried again with logs now: 
                                  ...
2023-09-01T17:12:10.017Z CNTRLR   [Node 019] Timed out while waiting for a response from the node (ZW0201)
2023-09-01 19:12:10.019 INFO Z-WAVE: [Node 019] Value updated: 37-2-targetValue true => true
2023-09-01 19:12:10.023 INFO Z-WAVE: [Node 019] Value updated: 37-2-currentValue false => true
2023-09-01T17:12:12.173Z CNTRLR   [Node 019] Timed out while waiting for a response from the node (ZW0201)
2023-09-01 19:12:25.673 INFO APP: GET /health/zwave 200 5.794 ms - 2140


2023-09-01 19:12:10.023 INFO Z-WAVE: [Node 019] Value updated: 37-2-currentValue false => true
2023-09-01T17:12:12.173Z CNTRLR   [Node 019] Timed out while waiting for a response from the node (ZW0201)
2023-09-01 19:12:25.673 INFO APP: GET /health/zwave 200 5.794 ms - 2140
2023-09-01T17:12:36.234Z CNTRLR   [Node 001] does not support CC Multilevel Sensor - discarding received command
                                  ...
2023-09-01 19:12:45.021 INFO Z-WAVE: [Node 001] Value updated: 114-0-manufacturerId 327 => 271
2023-09-01 19:12:45.024 INFO Z-WAVE: [Node 001] Value updated: 114-0-productType 1025 => 514
2023-09-01 19:12:45.027 INFO Z-WAVE: [Node 001] Value updated: 114-0-productId 257 => 4098
2023-09-01T17:12:46.034Z CNTRLR   [Node 017] Timed out while waiting for a response from the node (ZW0201)
2023-09-01 19:12:46.041 ERROR Z-WAVE-SERVER: Cannot check for firmware updates for node 17: Failed to query fingerprint from the node! (ZW0260)
ZWaveError: Cannot check for firmware updates for node 17: Failed to query fingerprint from the node! (ZW0260)
    at ZWaveController.getAvailableFirmwareUpdates (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:6521:10)
    at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:201:30)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:119:62)
2023-09-01 19:12:55.929 INFO APP: GET /health/zwave 200 3.638 ms - 2140
2023-09-01T17:13:07.851Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:08.859Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:08.934Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:08.958Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:09.129Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:09.184Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:09.271Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:09.431Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:09.456Z CNTRLR   [Node 001] in the process of replying to a NonceGet, won't send another NonceR
                                  eport
2023-09-01T17:13:09.647Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:09.750Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:09.790Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:09.988Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:09.997Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:10.023Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:10.104Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:10.138Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:10.205Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:10.276Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
2023-09-01T17:13:10.396Z CNTRLR   [Node 001] received GET-type command via broadcast - discarding...
023-09-01 19:13:26.100 INFO APP: GET /health/zwave 200 4.227 ms - 2140
2023-09-01 19:13:56.302 INFO APP: GET /health/zwave 200 4.693 ms - 2140
2023-09-01 19:14:26.464 INFO APP: GET /health/zwave 200 6.379 ms - 2140
2023-09-01 19:14:56.668 INFO APP: GET /health/zwave 200 8.545 ms - 2140
2023-09-01T17:15:00.305Z CNTRLR « [Node 001] received S2 nonce without an active transaction, not sure what to d
                                  o with it
2023-09-01T17:15:01.287Z CNTRLR   [Node 034] Timed out while waiting for a response from the node (ZW0201)
2023-09-01 19:15:01.290 INFO Z-WAVE: [Node 034] Value updated: 38-1-targetValue 0 => 30
2023-09-01 19:15:01.300 INFO Z-WAVE: [Node 034] Value updated: 38-1-currentValue 0 => 30
2023-09-01T17:15:06.473Z CNTRLR « [Node 001] received S2 nonce without an active transaction, not sure what to d
                                  o with it
2023-09-01T17:15:07.474Z CNTRLR   [Node 034] Timed out while waiting for a response from the node (ZW0201)
2023-09-01 19:15:26.812 INFO APP: GET /health/zwave 200 4.489 ms - 2140

**Comment by mimimi0815** [comment]
I have the same issue. I have to restart the zwave js-ui task that everything works well again. And then after some hours suddenly the z-wave devices stop working. I am using Homeassistant in the current version 2023.09.01 with the combo stick Nortek HUSBZB-1 ZWAVE/zigbee. Bevore it runs well over weeks without interruptions.

**Comment by magne74** [comment]
I updated the z-wave stick to firmware 7.19.4. That did the trick. Now everything is working just fine.
