### ISSUE TITLE
Z-Wave JS UI 2.0.0 & 2.0.1 Update - Healing Nodes / Rebuilding Routes Fails

### ISSUE THREAD

**Issue by neydah700** [hassio-addons/addon-zwave-js-ui#580]
# Problem/Motivation

After updating to 2.0.0 I get the following error when trying to heal a device 

"To assign a return route to the SUC (node ID 1), assignSUCReturnRoutes() must be used! (ZW0322) rebuildNodeRoutes undefined"

## Expected behavior

Expect devices to heal successful. 

## Actual behavior

Healing / Rebuilding routes fails

## Steps to reproduce

Attempt to heal a device. I am using a Z‐Stick Gen5 for my controller.

## Proposed changes

Unknown at this time.

**Comment by Gonioul** [comment]
2.0.0 is broken, try 2.0.1

**Comment by neydah700** [comment]
> 2.0.0 is broken, try 2.0.1

No dice. 2.0.1 still get the same error. Full error below

To assign a return route to the SUC (node ID 1), assignSUCReturnRoutes() must be used! (ZW0322)
ZWaveError: To assign a return route to the SUC (node ID 1), assignSUCReturnRoutes() must be used! (ZW0322)
    at ZWaveController.assignReturnRoutes (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:4568:10)
    at ZWaveController.rebuildNodeRoutesInternal (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:4233:18)
    at ZWaveController.rebuildNodeRoutes (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:4106:11)
    at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:81:33)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:125:62)

**Comment by tane64** [comment]
Same problem here. Need to rebuild routes after replacement of the Z-Stick ..

**Comment by neydah700** [comment]
Resolved with 2.1.0
