### ISSUE TITLE
devices unavailable after update to 2.0.0

### ISSUE THREAD

**Issue by maartenhendrix** [hassio-addons/addon-zwave-js-ui#582]
# Problem/Motivation
My z-wave devices are unavailable after updating to 2.0.0
logs show:
```
2023-09-27 21:42:15.610 INFO APP: GET /health/zwave 301 1.532 ms - 191
2023-09-27 21:42:19.105 WARN Z-WAVE-SERVER: Z-Wave JS no longer supports enabling error reporting. If you are using an application that integrates with Z-Wave JS and you receive this error, you may need to update the application.
2023-09-27 21:42:19.119 ERROR Z-WAVE-SERVER: The controller does not support soft reset or the soft reset feature has been disabled with a config option or the ZWAVEJS_DISABLE_SOFT_RESET environment variable. (ZW0111)
ZWaveError: The controller does not support soft reset or the soft reset feature has been disabled with a config option or the ZWAVEJS_DISABLE_SOFT_RESET environment variable. (ZW0111)
    at Driver.softReset (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:2473:10)
    at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/driver/message_handler.js:80:30)
    at Object.driver (/opt/node_modules/@zwave-js/server/dist/lib/server.js:41:91)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:125:99)
    at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:57:45)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/opt/node_modules/@zwave-js/server/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.dataMessage (/opt/node_modules/@zwave-js/server/node_modules/ws/lib/receiver.js:560:14)
    at /opt/node_modules/@zwave-js/server/node_modules/ws/lib/receiver.js:511:23
2023-09-27 21:42:32.976 INFO Z-WAVE: [Node 029] Metadata updated: 50-0-value-65537
```

## Expected behavior
z-wave devices available in home-assistant

## Actual behavior
devices show unavailable

## Steps to reproduce
update to version 2.0.0

## Versions
Home-Assistant: 2023.9.3
OS: 10.5
Addon: 2.0.0

related posts/tickets:
https://community.home-assistant.io/t/updated-ha-2023-9-2-2023-9-3-and-now-z-wave-add-on-no-longer-works/619202/10

https://github.com/home-assistant/addons/issues/3234

**Comment by Gonioul** [comment]
Seems ok with 9.0.1 now

**Comment by frenck** [comment]
Fixed in add-on version [2.0.1](https://github.com/hassio-addons/addon-zwave-js-ui/releases/tag/v2.0.1)

**Comment by maartenhendrix** [comment]
Thank you very much for the fast fix. It is working again

**Comment by ablyes** [comment]
I can see the 0.1.93
But obviously we are not talking about the same component. I’m lost. 
‘which part is the 2.0.1 ?

**Comment by nsleigh** [comment]
I am seeing this error after the 2.0.1 update (is there a way to downgrade to validate?):

2023-09-28T09:41:12.912Z CNTRLR   Serial API did not respond, giving up
2023-09-28T09:41:12.913Z DRIVER   Failed to initialize the driver: ZWaveError: The Serial API did not respond af
                                  ter soft-reset (ZW0100)
                                      at Driver.softResetInternal (/opt/node_modules/zwave-js/src/lib/driver/Dri
                                  ver.ts:2524:11)
                                      at Driver.initializeControllerAndNodes (/opt/node_modules/zwave-js/src/lib
                                  /driver/Driver.ts:1384:5)
                                      at Immediate.<anonymous> (/opt/node_modules/zwave-js/src/lib/driver/Driver
                                  .ts:1165:5)

**Comment by nsleigh** [comment]
> I am seeing this error after the 2.0.1 update (is there a way to downgrade to validate?):
> 
> 2023-09-28T09:41:12.912Z CNTRLR Serial API did not respond, giving up 2023-09-28T09:41:12.913Z DRIVER Failed to initialize the driver: ZWaveError: The Serial API did not respond af ter soft-reset (ZW0100) at Driver.softResetInternal (/opt/node_modules/zwave-js/src/lib/driver/Dri ver.ts:2524:11) at Driver.initializeControllerAndNodes (/opt/node_modules/zwave-js/src/lib /driver/Driver.ts:1384:5) at Immediate. (/opt/node_modules/zwave-js/src/lib/driver/Driver .ts:1165:5)

This resolved it https://github.com/hassio-addons/addon-zwave-js-ui/issues/584
