### ISSUE TITLE
Zwave Driver Constantly Failing

### ISSUE THREAD

**Issue by a-pir1** [hassio-addons/addon-zwave-js-ui#611]
I receive the following logs and lose control of all connected Zwave devices, prompting a total reboot of my Home Assistant Yellow.

Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200) at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:5176:23) at ZWaveController.identify (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:897:37) at Driver.initializeControllerAndNodes (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:1414:26) at Immediate.<anonymous> (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:1208:16) (ZW0100) 
Error: Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200) at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:5176:23) at ZWaveController.identify (/opt/node_modules/zwave-js/src/lib/controller/Controller.ts:897:37) at Driver.initializeControllerAndNodes (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:1414:26) at Immediate.<anonymous> (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:1208:16) (ZW0100)

As a point of reference, I was also having this issue with a different USB antenna and when using the official Zwave JS.

**Comment by a-pir1** [comment]
As a point of reference, I was also having this issue with a different USB antenna and when using the official Zwave JS.

**Comment by a-pir1** [comment]
Looks like the bus on my HASS Yellow was getting overwhelmed by my Google Coral, though it was sitting idle and not being used by any addons.  Z-wave has been working as expected since removal.
